// <auto-generated />
using System;
using Backend_GameDiscountNotifier.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_GameDiscountNotifier.Migrations
{
    [DbContext(typeof(MariaDbContext))]
    [Migration("20260706162920_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Backend_GameDiscountNotifier.Model.Contet.Joc", b =>
                {
                    b.Property<int>("IdJoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdJoc"));

                    b.Property<int>("IdSeller")
                        .HasColumnType("int");

                    b.Property<string>("Tipus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdJoc");

                    b.HasIndex("IdSeller");

                    b.HasIndex("Title");

                    b.ToTable("Jocs");
                });

            modelBuilder.Entity("Backend_GameDiscountNotifier.Model.Contet.JocEnPlataforma", b =>
                {
                    b.Property<int>("IdJocPlatataforma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdJocPlatataforma"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Enllaç")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdJoc")
                        .HasColumnType("int");

                    b.Property<int>("IdPlataforma")
                        .HasColumnType("int");

                    b.Property<string>("ImatgeLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PreuOriginal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdJocPlatataforma");

                    b.HasAlternateKey("IdJoc", "IdPlataforma");

                    b.HasIndex("IdPlataforma");

                    b.ToTable("JocsEnPlataformes");
                });

            modelBuilder.Entity("Backend_GameDiscountNotifier.Model.Contet.Oferta", b =>
                {
                    b.Property<string>("IdExtretOferta")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DadesJsonOferta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("DataFiOferta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("DataIniciOferta")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Descompte")
                        .HasColumnType("int");

                    b.Property<int>("IdJocPlatataforma")
                        .HasColumnType("int");

                    b.Property<decimal>("PreuMomentOferta")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("esGratis")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdExtretOferta");

                    b.HasIndex("IdJocPlatataforma");

                    b.ToTable("Ofertas");
                });

            modelBuilder.Entity("Backend_GameDiscountNotifier.Model.Contet.Plataforma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomPlataforma")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("NomPlataforma");

                    b.ToTable("Plataformes");
                });

            modelBuilder.Entity("Backend_GameDiscountNotifier.Model.Contet.SellerJoc", b =>
                {
                    b.Property<int>("IdSeller")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSeller"));

                    b.Property<string>("NomSeller")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdSeller");

                    b.HasIndex("NomSeller");

                    b.ToTable("SellersJocs");
                });

            modelBuilder.Entity("Backend_GameDiscountNotifier.Model.Contet.Joc", b =>
                {
                    b.HasOne("Backend_GameDiscountNotifier.Model.Contet.SellerJoc", "Seller")
                        .WithMany("Jocs")
                        .HasForeignKey("IdSeller")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Backend_GameDiscountNotifier.Model.Contet.JocEnPlataforma", b =>
                {
                    b.HasOne("Backend_GameDiscountNotifier.Model.Contet.Joc", "Joc")
                        .WithMany("JocEnPlataformes")
                        .HasForeignKey("IdJoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_GameDiscountNotifier.Model.Contet.Plataforma", "Plataforma")
                        .WithMany("JocsPlataforma")
                        .HasForeignKey("IdPlataforma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joc");

                    b.Navigation("Plataforma");
                });

            modelBuilder.Entity("Backend_GameDiscountNotifier.Model.Contet.Oferta", b =>
                {
                    b.HasOne("Backend_GameDiscountNotifier.Model.Contet.JocEnPlataforma", "JocPlatataforma")
                        .WithMany("Ofertas")
                        .HasForeignKey("IdJocPlatataforma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JocPlatataforma");
                });

            modelBuilder.Entity("Backend_GameDiscountNotifier.Model.Contet.Joc", b =>
                {
                    b.Navigation("JocEnPlataformes");
                });

            modelBuilder.Entity("Backend_GameDiscountNotifier.Model.Contet.JocEnPlataforma", b =>
                {
                    b.Navigation("Ofertas");
                });

            modelBuilder.Entity("Backend_GameDiscountNotifier.Model.Contet.Plataforma", b =>
                {
                    b.Navigation("JocsPlataforma");
                });

            modelBuilder.Entity("Backend_GameDiscountNotifier.Model.Contet.SellerJoc", b =>
                {
                    b.Navigation("Jocs");
                });
#pragma warning restore 612, 618
        }
    }
}
